<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\ConfiguredPricingCatalogSync\ConfiguredPricingCatalogSync.Core\ConfiguredPricingCatalogSync.Core.csproj" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.3" />
    <PackageReference Include="MongoDB.Driver" Version="3.11.2" />
  </ItemGroup>
</Project>
